pyproject.toml, uv.lock
This PR sets up the project with core and development dependencies:
- Added `fastapi[standard]` for building APIs with common extras included
- Added `ruff` for code linting and `pytest` for testing as development tools
=> chore: Setup FastAPI dependencies and dev tools

ruff.toml
This PR adds `Ruff` as the linter for the project, with configuration defined in a `ruff.toml` file.
=> chore: Added Ruff linter configuration

main.py
This PR adds the necessary CORS configuration to the FastAPI backend to allow communication with the `simulation-ui` app running on `http://localhost:5173` currently.
=> feat: Enabled CORS for frontend integration

src/models.py
This PR updates the `county_name` field from a plain `str` type to a `CountyName` enum. This change enforces stricter data validation and improves code maintainability by restricting county names to a predefined list (Taipei, Hsinchu, Taichung, Tainan).
=> chore: Replaced county name field with enum type

main.py
This PR introduces a simple HTTP POST handler at `/api/earthquake` for receiving simulated earthquake data from the `simulation-ui` frontend.
=> feat: Added POST endpoint for simulated earthquake data

ruff.toml, src/utils.py
This PR reduces Ruff's `line-length` setting from 120 to 88 to improve code readability by encouraging line breaks for long expressions. This helps avoid dense one-liners and promotes cleaner formatting, especially for function calls and complex logic.
=> chore: Updated Ruff line length limit

.env.example
This PR added `FRONTEND_BASE_URL` to the environment variable example to support proper CORS setup during local development.
=> chore: Added env example for CORS config

app/routers/earthquake.py, app/services/metrics.py
This PR introduces Prometheus metrics to monitor incoming earthquake data:
- `earthquake_occurrences`: Tracks the total number of earthquake data received.
- `earthquake_magnitude`: Captures the magnitude value of each earthquake data.
- `earthquake_depth`: Captures the focal depth of each earthquake data.
=> feat: Added earthquake data observation metrics

app/models/earthquake.py, app/services/earthquake.py
This PR made the following changes:
- Updated type annotations for certain fields in the `EarthquakeData` model from str to float where applicable (`magnitude_value`, `focal_depth`, etc.) to eliminate the need for runtime casting.
- Set a default value for `shaking_area` using `Field(default_factory=list)` to ensure it defaults to an empty list instead of None.
=> fix: Resolved earthquake data type

.env.example, app/main.py, app/services/metrics.py
This PR introduces two key changes:
1. Prometheus Metrics:
- Added a new `earthquake_intensity` gauge metric to export area-wise earthquake intensity.
- Metric is labeled with source, id, and area, and populated for each `shaking_area` from the earthquake data payload.
2. CORS Configuration:
- Removed use of the `FRONTEND_BASE_URL` environment variable.
- Replaced with a wildcard (`"*"`), allowing requests from any origin.
=> feat: Added earthquake area intensity metrics

.env.example, app/core/redis.py, app/main.py, app/models/settings.py, app/routers/earthquake.py, app/routers/settings.py, app/services/earthquake.py
This PR improves the flexibility of the alert suppress time setting by:
- Replacing the previously hardcoded 1-minute suppress time with a default value from `.env`
- Adding a new API handler at `/api/settings/alert-suppress-time` to allow users to update the suppress time from frontend.
- Storing the updated suppress time in Redis for persistence across sessions and scalability.
- Ensuring the system uses the Redis-stored value if available, falling back to the `.env` default otherwise.
Fix #27
=> fix: Resolved hardcoded alert suppress time issue

app/models/earthquake.py, app/routers/earthquake.py, app/services/earthquake.py
This PR change the data type of Alert to
```python!
class EarthquakeAlert(BaseModel):
id: str
source: str
origin_time: datetime
location: Location
severity_level: SeverityLevel
status: str
processing_furation: int
```
In addition, it adjusts the code inside function ```generate_alerts()```
=> fix: change Alert's data type from "EarthquakeEvent" to "EarthquakeAlert"

app/models/earthquake.py, app/models/enums.py, app/routers/earthquake.py, app/services/earthquake.py, app/services/metrics.py
This PR mainly add Prometheus event and alert metrics, including some minor changes : previous attribute ```status``` in EarthquakeAlert is changed to ```has_damage``` and ```needs_command_center```
There are some notes and discussion to be discussed with, but first you can just see if everything goes right
- Currently implementation of Alert metric, such as ```earthquake_alerts_damage```, ```earthquake_alerts_command_center```, ```earthquake_alerts_processing_duration``` will be scratched first with initial value (UNKNOWN = -1, UNKNOWN = -1, 0) and then be overwritten after the report.
- Report needs to specify the old alert's label : ```["source", "id", "location"]```, and need to compute ```processing_duration``` by the old alert's label ```origin_time```
- The Overwrite after the …
=> feat: Add Prometheus event and alert metrics

app/models/earthquake.py, app/models/enums.py, app/services/earthquake.py, app/services/metrics.py
This PR refactor the class ```SeverityLevel``` and ```EarthquakeAlert``` :
```python
class SeverityLevel(int, Enum):
NA = 0
L1 = 1
L2 = 2
```
```python
class EarthquakeAlert(EarthquakeEvent):
has_damage: TriState
needs_command_center: TriState
processing_duration: int
```
Fix #36
=> chore: refactor class SeverityLevel & EarthquakeAlert

.env.example, docker-compose.yml
This PR setups basic configuration of Grafana, you can follow the steps :
1. add your own ```GF_SECURITY_ADMIN_USER``` and ```GF_SECURITY_ADMIN_USER``` to .env (both ```admin``` in .env.example)
2. re-build the image and run
3. login and add Prometheus as a data source (left side bar : Connections -> Data sources)
4. you can now try anything such as create dashboards to visualize metrics
Fix #32
=> feat: Add Grafana configuration in docker-compose

app/main.py, app/routers/redis.py
This PR adds a new DELETE endpoint at `/api/redis/` to allow clearing the entire Redis cache. This endpoint is useful for clearing previously stored alerts or cached data during development and testing.
=> chore: Added endpoint to clear Redis cache

.gitignore, docker-compose.yml, grafana/dashboards/sample-dashboard.json, grafana/provisioning/dashboards/dashboards.yaml, grafana/provisioning/datasources/datasource.yml
This PR add the basic dashboard configuration with a simple dashboard sample, some notes below:
- you need to re-build and run
- your data source's name on the Grafana web UI needs to be exactly the same as the data source defined inside ```grafana/dashboards/sample-dashboard.json``` or ```grafana/provisioning/datasources/datasource.yml```, otherwise it will fail on connection
Fix #41
=> feat: Add Grafana dashboard configuration

app/models/earthquake.py, app/models/enums.py, app/services/earthquake.py
This PR refactor class ```EarthquakeAlert``` to 
```python
class EarthquakeAlert(EarthquakeEvent):
status: AlertStatus
has_damage: TriState
needs_command_center: TriState
processing_duration: int
```
with class ```AlertStatus``` be 
```python
class AlertStatus(int, Enum):
CLOSED = 1
OPEN = 0
AUTOCLOSED = -1
```
Note that you may need to clear redis first
=> chore: Refactor EarthquakeAlert class

app/core/redis.py, app/models/enums.py, app/routers/earthquake.py, app/services/earthquake.py
This PR updates the backend logic to filter cached earthquake alerts to include only those with an OPEN status.
=> chore: Filter alerts by open status

app/models/earthquake.py, app/routers/earthquake.py
This PR added PUT `/api/earthquake/alerts/{alert_id}` endpoint to handle the processing of earthquake alerts.
- The endpoint:
- Validates that the alert exists in Redis.
- Calculates and updates the alert’s `processing_duration` based on `processed_time` and `origin_time`.
- Removes the processed alert from Redis to free up memory.
- Future work: update relevant alert metrics.
=> feat: Added endpoint for processing earthquake alert

app/core/redis.py, app/routers/earthquake.py, app/routers/redis.py, app/routers/settings.py, app/services/earthquake.py
This PR refactors the application to use the async Redis client (`redis.asyncio`) instead of the synchronous `redis-py` client. This change is necessary to handle Redis operations efficiently in a non-blocking way, particularly for WebSocket communication and Redis Pub/Sub functionality in the future.
=> feat: Migrate to async Redis client

app/core/redis.py, app/core/redis_listener.py, app/main.py, app/routers/earthquake.py, app/services/earthquake.py, app/services/metrics.py, app/websockets/alerts_ws.py, app/websockets/manager.py, pyproject.toml, uv.lock
This PR implements real-time earthquake alert broadcasting using Redis pub/sub and WebSocket integration. The goal is to allow all connected clients in frontend to receive `AUTO_CLOSED` alerts (and potentially other alert types) instantly and reliably.
Fix #49
=> feat: Real-time alert broadcasting via Redis pub/sub and WebSocket

app/core/redis.py, app/main.py
This PR adds a `/health` endpoint to the backend service that verifies connectivity to the Redis instance. It performs a simple PING operation using the Redis client to ensure the service is available and responsive.
=> chore: Added health check endpoint

app/routers/earthquake.py
This PR reverted the alert expiration logic to consider alerts not responded after 1 hour as expired instead of 1 min set previously.
=> chore: Reverted alert expiration time

app/websockets/alerts_ws.py
This PR introduces a periodic ping system for the WebSocket endpoint (`/ws/alerts`) to ensure client connections remain alive, especially when idle for extended periods.
=> chore: Added WebSocket ping mechanism for connection keep-alive

app/routers/earthquake.py, app/utils/logger.py, tests/utils/test_logger.py
This PR introduces a centralized logging setup to enable consistent, structured logging across the application. The logger is defined once and can be reused in all modules, including routers, background tasks, and utilities.
=> feat: Added centralized application logger

tests/conftest.py, tests/routers/test_earthquake.py
This PR introduces the remaining tests for earthquake router, with some space for improvement:
1. logger hasn't been added into the router test
2. test `test_get_realtime_earthquake_data` isn't finished yet
=> feat: Added earthquake router related tests
