TSMC-NTU-G4/backend

- .github/workflows/pull-request-title-validator.yml
This PR introduces a GitHub Actions workflow to automatically validate pull request titles. It ensures that PR titles follow a conventional format and start with one of the allowed types: `fix`, `feat`, or `chore`.
> feat: Added PR title validation workflow

- main.py
This PR sets up a minimal FastAPI application as the backend entry point.
> feat: Initialized FastAPI app with basic setup

- .github/workflows/build.yml
This PR introduces a GitHub Actions workflow to automatically check code style and linting using Ruff.
> feat: Added workflow for Ruff linting

- src/models.py
This PR adds a Pydantic model to process simulated earthquake data sent from the `simulation-ui` frontend via POST requests.
> feat: Added earthquake data model

- main.py
- src/models.py
- src/utils.py
This PR adds functionality to generate earthquake events for each county based on incoming earthquake data.
> feat: Implemented earthquake event generation logic

- .gitignore
- pyproject.toml
- src/main.py
- uv.lock
This PR introduced the `python-dotenv` package to load environment variables from a `.env` file, replacing hardcoded values.
> feat: Added env variable management

- Dockerfile
- app/main.py
This PR adds `--reload` to the Dockerfile to enable automatic server reload on code changes. It also introduces a simple welcome message in `main.py` to verify that reloading works as expected.
> chore: Added root endpoint

- .env.example
- app/core/redis.py
- app/models/earthquake.py
- app/routers/earthquake.py
- app/services/earthquake.py
- app/services/metrics.py
- docker-compose.yml
- pyproject.toml
- uv.lock
This PR introduces alert generation logic and implements suppression of redundant events using Redis. The core changes include:
- Added logic to generate alerts based on incoming events.
- Integrated Redis caching to store generated alerts temporarily.
- Implemented suppression mechanism:
- Events occurring in the same location as a cached alert are ignored if:
-  The event's severity level is less than or equal to the alert's severity.
- The event occurs within the defined suppression window since the alert was cached.
> feat: Implemented alert generation functionality

- app/main.py
- app/models/response.py
- app/routers/earthquake.py
- app/routers/settings.py
This PR introduces a generic Response model that standardizes the structure of all API responses. By using this model, all responses will consistently include both message and data fields, improving consistency across the API.
> chore: Unified API response with generic model

- app/models/earthquake.py
- app/routers/earthquake.py
This PR introduces a new GET endpoint `/api/earthquake/alerts` that retrieves all cached earthquake alert data stored in Redis.
> feat: Added endpoint to fetch earthquake alerts

- app/routers/earthquake.py
- app/services/earthquake.py
This PR refactors the repeated logic for processing earthquake data across multiple endpoints by extracting it into a reusable `process_earthquake_data` function.
> chore: Refactored earthquake processing logic

- app/routers/earthquake.py
- app/services/earthquake.py
- app/services/metrics.py
This PR mainly contributes to:
1. Add additional Alert metric ```earthquake_alerts_processed_total```
2. Add ```observe_earthquake_alert_report()``` which is then wrapped inside ```update_alert_metrics()``` function
> chore: Added update_alert_metrics()

- .github/workflows/deploy.yml
This PR introduces a GitHub Actions workflow that automatically pushes the Docker image to Google Cloud Artifact Registry when the Build workflow completes successfully on the main branch.
> feat: Added workflow for image push to GCP Artifact Registry

- app/routers/earthquake.py
- app/utils/realtime_data_handler.py
This PR updates the `/api/earthquake/realtime` endpoint to construct and return a properly typed `EarthquakeData` Pydantic model instead of a raw dictionary.
> chore: Format realtime earthquake data

- .github/workflows/build.yml
- sonar-project.properties
This PR sets up SonarCloud integration to enable static code analysis and test coverage reporting for the backend service via GitHub Actions.
> feat: Integrated SonarCloud Analysis in CI

- app/routers/earthquake.py
This PR adds support for broadcasting realtime earthquake alerts to connected WebSocket clients via Redis Pub/Sub.
> feat: Published realtime earthquake alerts to Redis channel

- tests/models/test_custom_base_model.py
- tests/models/test_earthquake_models.py
- tests/models/test_enums.py
- tests/models/test_response_model.py
- tests/models/test_settings_model.py
This PR introduces unit tests to ensure correctness and serialization behavior of various `Pydantic` models and enums used in the project.
> feat: Added unit tests for Pydantic models

- tests/core/test_redis.py
- tests/core/test_redis_listener.py
This PR added comprehensive unit tests for the Redis pub/sub alert listener in `app.core.redis_listener`.
> feat: Added unit tests for Redis

- tests/services/test_earthquake.py
- tests/services/test_metrics.py
This PR introduces unit tests for the `earthquake` and `metrics` services.
> feat: Added unit tests for services module

- tests/test_main.py
- tests/websockets/test_manager.py
This PR adds unit tests for the `WebSocketManager` class to ensure reliable WebSocket connection management.
> feat: Added unit tests for websocket module

- app/services/metrics.py
- tests/services/test_metrics.py
This PR add `earthquake_id` label in `earthquake_alerts_damage`, `earthquake_alerts_command_center` metric
> chore: Added earthquake_id label
